### ISSUE TITLE
Workflow fails with AttributeError: 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by brokenarc** [anyboxhq/anybox-alfred-workflow#5]
I get the stack trace below whenever I activate the Anybox workflow.

```
[05:59:04.443] Anybox[Script Filter] Queuing argument 'python'
[05:59:04.619] Anybox[Script Filter] Script with argv 'python' finished
[05:59:04.625] ERROR: Anybox[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/shannon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/488BBB8C-FB6A-4713-AC4E-DA74EEDFFED4", line 211, in <module>
    links = get_links()
  File "/Users/shannon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/488BBB8C-FB6A-4713-AC4E-DA74EEDFFED4", line 128, in get_links
    'subtitle': format_subtitle(link),
  File "/Users/shannon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/488BBB8C-FB6A-4713-AC4E-DA74EEDFFED4", line 64, in format_subtitle
    subtitle = format_url(link['url']) + date
  File "/Users/shannon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/488BBB8C-FB6A-4713-AC4E-DA74EEDFFED4", line 40, in format_url
    return url.removeprefix('https://')
AttributeError: 'str' object has no attribute 'removeprefix'
```

Environment details:

- anybox-alfred-workflow 2.0.1
- Anybox 2.0.3 (140)
- Alfred 5.1.3 (2175)
- `/usr/bin/python3` 3.8.2
- `/usr/bin/env python3` 3.11.5
- macOS Sonoma 14.0

**Comment by francisfeng** [comment]
Can you update the `/usr/bin/python3` to 3.9?

It looks like `removeprefix` was introduced in Python 3.9.

**Comment by brokenarc** [comment]
After I installed the XCode 15 Command Line Tools, the workflow works as expected.

Please consider updating the README to list the XCode 15 Command Line Tools as a dependency for these reasons:

- Without using the debugging tools in Alfred, it was impossible to know what happened. Even if your target users are developers, this is an annoyance. Non-developers might simply conclude that Anybox is broken.
- Installing a new version of Python from python.org does not change `/usr/bin/python3`.
- The [Python docs](https://docs.python.org/3/using/mac.html#getting-and-installing-macpython) recommend against changing the `/usr/bin/python3` version manually: "You should never modify or delete these, as they are Apple-controlled..."

Thanks!
